// <auto-generated />
using System;
using pos_api_app.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace posapiapp.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20250724022142_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pos_api_app.Model.Entities.Employee", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("firstname");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<Guid?>("RoleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("role_guid");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Guid");

                    b.HasIndex("RoleGuid");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("tb_m_employee");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.Product", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("BarcodeID")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("barcode_id");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Guid");

                    b.ToTable("tb_m_product");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.Role", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Guid");

                    b.ToTable("tb_m_role");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<Guid?>("EmployeeGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_guid");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("TotalAmmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_ammount");

                    b.Property<DateTime>("TransactionsDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Guid");

                    b.HasIndex("EmployeeGuid");

                    b.ToTable("tb_tr_transaction");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.TransactionItem", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("PriceGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("price_guid");

                    b.Property<Guid?>("ProductGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("product_guid");

                    b.Property<float>("Quantity")
                        .HasColumnType("real")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid?>("TransactionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_guid");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Guid");

                    b.HasIndex("PriceGuid");

                    b.HasIndex("ProductGuid");

                    b.HasIndex("TransactionGuid");

                    b.ToTable("tb_m_transaction_item");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.Unit", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Guid");

                    b.ToTable("tb_m_unit");
                });

            modelBuilder.Entity("pos_api_app.Models.Entities.Price", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("ProductGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("product_guid");

                    b.Property<Guid?>("UnitGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("price_guid");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Guid");

                    b.HasIndex("ProductGuid");

                    b.HasIndex("UnitGuid");

                    b.ToTable("tb_tr_price");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.Employee", b =>
                {
                    b.HasOne("pos_api_app.Model.Entities.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleGuid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.Transaction", b =>
                {
                    b.HasOne("pos_api_app.Model.Entities.Employee", "Employee")
                        .WithMany("Transactions")
                        .HasForeignKey("EmployeeGuid");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.TransactionItem", b =>
                {
                    b.HasOne("pos_api_app.Models.Entities.Price", "Price")
                        .WithMany("TransactionItems")
                        .HasForeignKey("PriceGuid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("pos_api_app.Model.Entities.Product", "Product")
                        .WithMany("TransactionItems")
                        .HasForeignKey("ProductGuid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("pos_api_app.Model.Entities.Transaction", "Transaction")
                        .WithMany("TransactionItems")
                        .HasForeignKey("TransactionGuid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Price");

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("pos_api_app.Models.Entities.Price", b =>
                {
                    b.HasOne("pos_api_app.Model.Entities.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductGuid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("pos_api_app.Model.Entities.Unit", "Unit")
                        .WithMany("Prices")
                        .HasForeignKey("UnitGuid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.Employee", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.Product", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("TransactionItems");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.Transaction", b =>
                {
                    b.Navigation("TransactionItems");
                });

            modelBuilder.Entity("pos_api_app.Model.Entities.Unit", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("pos_api_app.Models.Entities.Price", b =>
                {
                    b.Navigation("TransactionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
